name: Matrix Demo
on: push 
jobs: 
  continue-on-error: true # runs all the job in the matrix even if one fails. 

  build:
    strategy: 
       matrix:
       
         # add the matrix values here
        node-version: [18, 20]
        operating-system: [ubuntu-latest, windows-latest, macos-latest] 
       runs-on: ${{ matrix.operating-system }} 
       include:  # make an exclusive combination for this 
          - node-version: 18
            operating-system: ubuntu-latest
       steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Setup nodejs
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Lint code
          run: npm run lint
        - name: Test code
          run: npm run test 
  